name: SwiftLint
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**.swift'

jobs:
  build:
    name: Run SwiftLint
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run SwiftLint
      run: |
        swiftlint lint --reporter github-actions-logging
