name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    name: Test
    runs-on: macOS-11

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        ./scripts/unittests.sh
